# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default=0)),
                ('pax', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=10)),
                ('table', models.IntegerField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
    ]
